@startuml

class RestaurantsController <</api/restaurants>> {
    <<Get>> <</>> Restaurant[] get(String location)
}

class InvitationController <</api/invitation>> {
    <<Post>> <</>> void post(Invitation invitation)
}

class LunchController <</api/lunch>> {
    <<Post>> <</>> void post(Lunch lunch)
    <<Delete>> <</>> void delete(Lunch lunch)
}

class MeController <</api/me>> {
    <<Get>> <</>> User get() // returns the current user
    <<Get>> <</lunches>> Lunch[] lunches()
    <<Get>> <</invitations>> Invitation invitations()
    <<Get>> <</friends>> User[] friends()
}

class FriendsController <</api/friends>>{
    <<Get>> <</suggest>> User[] get() //returns all users not friends so far
    <<Post>> <</>> void add(Friendship friendship)
}

@enduml